# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/Users/a12042/Development/instant_db;/Users/a12042/Development/instant_db")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "Runtime;Development")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_DEVELOPMENT_DESCRIPTION "Headers and development libraries")
set(CPACK_COMPONENT_DEVELOPMENT_DISPLAY_NAME "Development Files")
set(CPACK_COMPONENT_RUNTIME_DESCRIPTION "InstantDB server and client tools")
set(CPACK_COMPONENT_RUNTIME_DISPLAY_NAME "InstantDB Runtime")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/local/Cellar/cmake/3.29.0/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "InstantDB built using CMake")
set(CPACK_DMG_BACKGROUND_IMAGE "/Users/a12042/Development/instant_db/packaging/macos/background.png")
set(CPACK_DMG_DS_STORE_SETUP_SCRIPT "/Users/a12042/Development/instant_db/packaging/macos/setup.scpt")
set(CPACK_DMG_FORMAT "UDBZ")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_DMG_VOLUME_NAME "InstantDB")
set(CPACK_GENERATOR "TGZ;ZIP")
set(CPACK_IGNORE_FILES "/build/;/\.git/;/\.github/;\.gitignore;\.DS_Store;/\.vscode/;/\.idea/;CMakeCache\.txt;CMakeFiles;Makefile;cmake_install\.cmake;CPackConfig\.cmake;CPackSourceConfig\.cmake;_CPack_Packages;\.tar\.gz$;\.zip$")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/Users/a12042/Development/instant_db;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "InstantDB")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "InstantDB")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJDUMP_EXECUTABLE "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump")
set(CPACK_OSX_SYSROOT "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk")
set(CPACK_OUTPUT_CONFIG_FILE "/Users/a12042/Development/instant_db/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "support@instantdb.com")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/Users/a12042/Development/instant_db/README.md")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Real-time database with WebAssembly module support")
set(CPACK_PACKAGE_FILE_NAME "InstantDB-0.1.0-Source")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://instantdb.com")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "InstantDB")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "InstantDB")
set(CPACK_PACKAGE_NAME "InstantDB")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "InstantDB Project")
set(CPACK_PACKAGE_VERSION "0.1.0")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "/Users/a12042/Development/instant_db/LICENSE")
set(CPACK_RESOURCE_FILE_README "/Users/a12042/Development/instant_db/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/local/Cellar/cmake/3.29.0/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "/build/;/\.git/;/\.github/;\.gitignore;\.DS_Store;/\.vscode/;/\.idea/;CMakeCache\.txt;CMakeFiles;Makefile;cmake_install\.cmake;CPackConfig\.cmake;CPackSourceConfig\.cmake;_CPack_Packages;\.tar\.gz$;\.zip$")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/Users/a12042/Development/instant_db;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/a12042/Development/instant_db/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "InstantDB-0.1.0-Source")
set(CPACK_SOURCE_TOPLEVEL_TAG "Darwin-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Darwin")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Darwin-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/a12042/Development/instant_db/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
