# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.29.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.29.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/a12042/Development/instant_db

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/a12042/Development/instant_db

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/local/Cellar/cmake/3.29.0/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/local/Cellar/cmake/3.29.0/bin/cpack --config ./CPackSourceConfig.cmake /Users/a12042/Development/instant_db/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.29.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.29.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Runtime\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.29.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.29.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.29.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.29.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.29.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.29.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/a12042/Development/instant_db/CMakeFiles /Users/a12042/Development/instant_db//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/a12042/Development/instant_db/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named storage

# Build rule for target.
storage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 storage
.PHONY : storage

# fast build rule for target.
storage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/storage.dir/build.make CMakeFiles/storage.dir/build
.PHONY : storage/fast

#=============================================================================
# Target rules for targets named changefeed_engine

# Build rule for target.
changefeed_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 changefeed_engine
.PHONY : changefeed_engine

# fast build rule for target.
changefeed_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/changefeed_engine.dir/build.make CMakeFiles/changefeed_engine.dir/build
.PHONY : changefeed_engine/fast

#=============================================================================
# Target rules for targets named sql_engine

# Build rule for target.
sql_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sql_engine
.PHONY : sql_engine

# fast build rule for target.
sql_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sql_engine.dir/build.make CMakeFiles/sql_engine.dir/build
.PHONY : sql_engine/fast

#=============================================================================
# Target rules for targets named websocket_server

# Build rule for target.
websocket_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 websocket_server
.PHONY : websocket_server

# fast build rule for target.
websocket_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_server.dir/build.make CMakeFiles/websocket_server.dir/build
.PHONY : websocket_server/fast

#=============================================================================
# Target rules for targets named common_lib

# Build rule for target.
common_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common_lib
.PHONY : common_lib

# fast build rule for target.
common_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_lib.dir/build.make CMakeFiles/common_lib.dir/build
.PHONY : common_lib/fast

#=============================================================================
# Target rules for targets named wasm_engine

# Build rule for target.
wasm_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasm_engine
.PHONY : wasm_engine

# fast build rule for target.
wasm_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasm_engine.dir/build.make CMakeFiles/wasm_engine.dir/build
.PHONY : wasm_engine/fast

#=============================================================================
# Target rules for targets named grpc_service

# Build rule for target.
grpc_service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grpc_service
.PHONY : grpc_service

# fast build rule for target.
grpc_service/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_service.dir/build.make CMakeFiles/grpc_service.dir/build
.PHONY : grpc_service/fast

#=============================================================================
# Target rules for targets named instantdb_demo

# Build rule for target.
instantdb_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 instantdb_demo
.PHONY : instantdb_demo

# fast build rule for target.
instantdb_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_demo.dir/build.make CMakeFiles/instantdb_demo.dir/build
.PHONY : instantdb_demo/fast

#=============================================================================
# Target rules for targets named instantdb_sql

# Build rule for target.
instantdb_sql: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 instantdb_sql
.PHONY : instantdb_sql

# fast build rule for target.
instantdb_sql/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_sql.dir/build.make CMakeFiles/instantdb_sql.dir/build
.PHONY : instantdb_sql/fast

#=============================================================================
# Target rules for targets named instantdb_init

# Build rule for target.
instantdb_init: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 instantdb_init
.PHONY : instantdb_init

# fast build rule for target.
instantdb_init/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_init.dir/build.make CMakeFiles/instantdb_init.dir/build
.PHONY : instantdb_init/fast

#=============================================================================
# Target rules for targets named instantdb_server

# Build rule for target.
instantdb_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 instantdb_server
.PHONY : instantdb_server

# fast build rule for target.
instantdb_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_server.dir/build.make CMakeFiles/instantdb_server.dir/build
.PHONY : instantdb_server/fast

#=============================================================================
# Target rules for targets named instantdb

# Build rule for target.
instantdb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 instantdb
.PHONY : instantdb

# fast build rule for target.
instantdb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb.dir/build.make CMakeFiles/instantdb.dir/build
.PHONY : instantdb/fast

#=============================================================================
# Target rules for targets named instantdb_client

# Build rule for target.
instantdb_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 instantdb_client
.PHONY : instantdb_client

# fast build rule for target.
instantdb_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_client.dir/build.make CMakeFiles/instantdb_client.dir/build
.PHONY : instantdb_client/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) $(MAKESILENT) -f _deps/spdlog-build/CMakeFiles/spdlog.dir/build.make _deps/spdlog-build/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f _deps/fmt-build/CMakeFiles/fmt.dir/build.make _deps/fmt-build/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

generated/instantdb.grpc.pb.o: generated/instantdb.grpc.pb.cc.o
.PHONY : generated/instantdb.grpc.pb.o

# target to build an object file
generated/instantdb.grpc.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_service.dir/build.make CMakeFiles/grpc_service.dir/generated/instantdb.grpc.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_client.dir/build.make CMakeFiles/instantdb_client.dir/generated/instantdb.grpc.pb.cc.o
.PHONY : generated/instantdb.grpc.pb.cc.o

generated/instantdb.grpc.pb.i: generated/instantdb.grpc.pb.cc.i
.PHONY : generated/instantdb.grpc.pb.i

# target to preprocess a source file
generated/instantdb.grpc.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_service.dir/build.make CMakeFiles/grpc_service.dir/generated/instantdb.grpc.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_client.dir/build.make CMakeFiles/instantdb_client.dir/generated/instantdb.grpc.pb.cc.i
.PHONY : generated/instantdb.grpc.pb.cc.i

generated/instantdb.grpc.pb.s: generated/instantdb.grpc.pb.cc.s
.PHONY : generated/instantdb.grpc.pb.s

# target to generate assembly for a file
generated/instantdb.grpc.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_service.dir/build.make CMakeFiles/grpc_service.dir/generated/instantdb.grpc.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_client.dir/build.make CMakeFiles/instantdb_client.dir/generated/instantdb.grpc.pb.cc.s
.PHONY : generated/instantdb.grpc.pb.cc.s

generated/instantdb.pb.o: generated/instantdb.pb.cc.o
.PHONY : generated/instantdb.pb.o

# target to build an object file
generated/instantdb.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_service.dir/build.make CMakeFiles/grpc_service.dir/generated/instantdb.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_client.dir/build.make CMakeFiles/instantdb_client.dir/generated/instantdb.pb.cc.o
.PHONY : generated/instantdb.pb.cc.o

generated/instantdb.pb.i: generated/instantdb.pb.cc.i
.PHONY : generated/instantdb.pb.i

# target to preprocess a source file
generated/instantdb.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_service.dir/build.make CMakeFiles/grpc_service.dir/generated/instantdb.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_client.dir/build.make CMakeFiles/instantdb_client.dir/generated/instantdb.pb.cc.i
.PHONY : generated/instantdb.pb.cc.i

generated/instantdb.pb.s: generated/instantdb.pb.cc.s
.PHONY : generated/instantdb.pb.s

# target to generate assembly for a file
generated/instantdb.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_service.dir/build.make CMakeFiles/grpc_service.dir/generated/instantdb.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_client.dir/build.make CMakeFiles/instantdb_client.dir/generated/instantdb.pb.cc.s
.PHONY : generated/instantdb.pb.cc.s

src/changefeed/changefeed_engine.o: src/changefeed/changefeed_engine.cpp.o
.PHONY : src/changefeed/changefeed_engine.o

# target to build an object file
src/changefeed/changefeed_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/changefeed_engine.dir/build.make CMakeFiles/changefeed_engine.dir/src/changefeed/changefeed_engine.cpp.o
.PHONY : src/changefeed/changefeed_engine.cpp.o

src/changefeed/changefeed_engine.i: src/changefeed/changefeed_engine.cpp.i
.PHONY : src/changefeed/changefeed_engine.i

# target to preprocess a source file
src/changefeed/changefeed_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/changefeed_engine.dir/build.make CMakeFiles/changefeed_engine.dir/src/changefeed/changefeed_engine.cpp.i
.PHONY : src/changefeed/changefeed_engine.cpp.i

src/changefeed/changefeed_engine.s: src/changefeed/changefeed_engine.cpp.s
.PHONY : src/changefeed/changefeed_engine.s

# target to generate assembly for a file
src/changefeed/changefeed_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/changefeed_engine.dir/build.make CMakeFiles/changefeed_engine.dir/src/changefeed/changefeed_engine.cpp.s
.PHONY : src/changefeed/changefeed_engine.cpp.s

src/changefeed/sql_subscription.o: src/changefeed/sql_subscription.cpp.o
.PHONY : src/changefeed/sql_subscription.o

# target to build an object file
src/changefeed/sql_subscription.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/changefeed_engine.dir/build.make CMakeFiles/changefeed_engine.dir/src/changefeed/sql_subscription.cpp.o
.PHONY : src/changefeed/sql_subscription.cpp.o

src/changefeed/sql_subscription.i: src/changefeed/sql_subscription.cpp.i
.PHONY : src/changefeed/sql_subscription.i

# target to preprocess a source file
src/changefeed/sql_subscription.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/changefeed_engine.dir/build.make CMakeFiles/changefeed_engine.dir/src/changefeed/sql_subscription.cpp.i
.PHONY : src/changefeed/sql_subscription.cpp.i

src/changefeed/sql_subscription.s: src/changefeed/sql_subscription.cpp.s
.PHONY : src/changefeed/sql_subscription.s

# target to generate assembly for a file
src/changefeed/sql_subscription.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/changefeed_engine.dir/build.make CMakeFiles/changefeed_engine.dir/src/changefeed/sql_subscription.cpp.s
.PHONY : src/changefeed/sql_subscription.cpp.s

src/cmd/grpc_client.o: src/cmd/grpc_client.cpp.o
.PHONY : src/cmd/grpc_client.o

# target to build an object file
src/cmd/grpc_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_client.dir/build.make CMakeFiles/instantdb_client.dir/src/cmd/grpc_client.cpp.o
.PHONY : src/cmd/grpc_client.cpp.o

src/cmd/grpc_client.i: src/cmd/grpc_client.cpp.i
.PHONY : src/cmd/grpc_client.i

# target to preprocess a source file
src/cmd/grpc_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_client.dir/build.make CMakeFiles/instantdb_client.dir/src/cmd/grpc_client.cpp.i
.PHONY : src/cmd/grpc_client.cpp.i

src/cmd/grpc_client.s: src/cmd/grpc_client.cpp.s
.PHONY : src/cmd/grpc_client.s

# target to generate assembly for a file
src/cmd/grpc_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_client.dir/build.make CMakeFiles/instantdb_client.dir/src/cmd/grpc_client.cpp.s
.PHONY : src/cmd/grpc_client.cpp.s

src/cmd/instantdb_cli.o: src/cmd/instantdb_cli.cpp.o
.PHONY : src/cmd/instantdb_cli.o

# target to build an object file
src/cmd/instantdb_cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb.dir/build.make CMakeFiles/instantdb.dir/src/cmd/instantdb_cli.cpp.o
.PHONY : src/cmd/instantdb_cli.cpp.o

src/cmd/instantdb_cli.i: src/cmd/instantdb_cli.cpp.i
.PHONY : src/cmd/instantdb_cli.i

# target to preprocess a source file
src/cmd/instantdb_cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb.dir/build.make CMakeFiles/instantdb.dir/src/cmd/instantdb_cli.cpp.i
.PHONY : src/cmd/instantdb_cli.cpp.i

src/cmd/instantdb_cli.s: src/cmd/instantdb_cli.cpp.s
.PHONY : src/cmd/instantdb_cli.s

# target to generate assembly for a file
src/cmd/instantdb_cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb.dir/build.make CMakeFiles/instantdb.dir/src/cmd/instantdb_cli.cpp.s
.PHONY : src/cmd/instantdb_cli.cpp.s

src/cmd/instantdb_init.o: src/cmd/instantdb_init.cpp.o
.PHONY : src/cmd/instantdb_init.o

# target to build an object file
src/cmd/instantdb_init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_init.dir/build.make CMakeFiles/instantdb_init.dir/src/cmd/instantdb_init.cpp.o
.PHONY : src/cmd/instantdb_init.cpp.o

src/cmd/instantdb_init.i: src/cmd/instantdb_init.cpp.i
.PHONY : src/cmd/instantdb_init.i

# target to preprocess a source file
src/cmd/instantdb_init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_init.dir/build.make CMakeFiles/instantdb_init.dir/src/cmd/instantdb_init.cpp.i
.PHONY : src/cmd/instantdb_init.cpp.i

src/cmd/instantdb_init.s: src/cmd/instantdb_init.cpp.s
.PHONY : src/cmd/instantdb_init.s

# target to generate assembly for a file
src/cmd/instantdb_init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_init.dir/build.make CMakeFiles/instantdb_init.dir/src/cmd/instantdb_init.cpp.s
.PHONY : src/cmd/instantdb_init.cpp.s

src/cmd/instantdb_server.o: src/cmd/instantdb_server.cpp.o
.PHONY : src/cmd/instantdb_server.o

# target to build an object file
src/cmd/instantdb_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_server.dir/build.make CMakeFiles/instantdb_server.dir/src/cmd/instantdb_server.cpp.o
.PHONY : src/cmd/instantdb_server.cpp.o

src/cmd/instantdb_server.i: src/cmd/instantdb_server.cpp.i
.PHONY : src/cmd/instantdb_server.i

# target to preprocess a source file
src/cmd/instantdb_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_server.dir/build.make CMakeFiles/instantdb_server.dir/src/cmd/instantdb_server.cpp.i
.PHONY : src/cmd/instantdb_server.cpp.i

src/cmd/instantdb_server.s: src/cmd/instantdb_server.cpp.s
.PHONY : src/cmd/instantdb_server.s

# target to generate assembly for a file
src/cmd/instantdb_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_server.dir/build.make CMakeFiles/instantdb_server.dir/src/cmd/instantdb_server.cpp.s
.PHONY : src/cmd/instantdb_server.cpp.s

src/cmd/prototype_demo.o: src/cmd/prototype_demo.cpp.o
.PHONY : src/cmd/prototype_demo.o

# target to build an object file
src/cmd/prototype_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_demo.dir/build.make CMakeFiles/instantdb_demo.dir/src/cmd/prototype_demo.cpp.o
.PHONY : src/cmd/prototype_demo.cpp.o

src/cmd/prototype_demo.i: src/cmd/prototype_demo.cpp.i
.PHONY : src/cmd/prototype_demo.i

# target to preprocess a source file
src/cmd/prototype_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_demo.dir/build.make CMakeFiles/instantdb_demo.dir/src/cmd/prototype_demo.cpp.i
.PHONY : src/cmd/prototype_demo.cpp.i

src/cmd/prototype_demo.s: src/cmd/prototype_demo.cpp.s
.PHONY : src/cmd/prototype_demo.s

# target to generate assembly for a file
src/cmd/prototype_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_demo.dir/build.make CMakeFiles/instantdb_demo.dir/src/cmd/prototype_demo.cpp.s
.PHONY : src/cmd/prototype_demo.cpp.s

src/cmd/sql_demo.o: src/cmd/sql_demo.cpp.o
.PHONY : src/cmd/sql_demo.o

# target to build an object file
src/cmd/sql_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_sql.dir/build.make CMakeFiles/instantdb_sql.dir/src/cmd/sql_demo.cpp.o
.PHONY : src/cmd/sql_demo.cpp.o

src/cmd/sql_demo.i: src/cmd/sql_demo.cpp.i
.PHONY : src/cmd/sql_demo.i

# target to preprocess a source file
src/cmd/sql_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_sql.dir/build.make CMakeFiles/instantdb_sql.dir/src/cmd/sql_demo.cpp.i
.PHONY : src/cmd/sql_demo.cpp.i

src/cmd/sql_demo.s: src/cmd/sql_demo.cpp.s
.PHONY : src/cmd/sql_demo.s

# target to generate assembly for a file
src/cmd/sql_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/instantdb_sql.dir/build.make CMakeFiles/instantdb_sql.dir/src/cmd/sql_demo.cpp.s
.PHONY : src/cmd/sql_demo.cpp.s

src/common/config.o: src/common/config.cpp.o
.PHONY : src/common/config.o

# target to build an object file
src/common/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_lib.dir/build.make CMakeFiles/common_lib.dir/src/common/config.cpp.o
.PHONY : src/common/config.cpp.o

src/common/config.i: src/common/config.cpp.i
.PHONY : src/common/config.i

# target to preprocess a source file
src/common/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_lib.dir/build.make CMakeFiles/common_lib.dir/src/common/config.cpp.i
.PHONY : src/common/config.cpp.i

src/common/config.s: src/common/config.cpp.s
.PHONY : src/common/config.s

# target to generate assembly for a file
src/common/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_lib.dir/build.make CMakeFiles/common_lib.dir/src/common/config.cpp.s
.PHONY : src/common/config.cpp.s

src/common/metrics.o: src/common/metrics.cpp.o
.PHONY : src/common/metrics.o

# target to build an object file
src/common/metrics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_lib.dir/build.make CMakeFiles/common_lib.dir/src/common/metrics.cpp.o
.PHONY : src/common/metrics.cpp.o

src/common/metrics.i: src/common/metrics.cpp.i
.PHONY : src/common/metrics.i

# target to preprocess a source file
src/common/metrics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_lib.dir/build.make CMakeFiles/common_lib.dir/src/common/metrics.cpp.i
.PHONY : src/common/metrics.cpp.i

src/common/metrics.s: src/common/metrics.cpp.s
.PHONY : src/common/metrics.s

# target to generate assembly for a file
src/common/metrics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common_lib.dir/build.make CMakeFiles/common_lib.dir/src/common/metrics.cpp.s
.PHONY : src/common/metrics.cpp.s

src/grpc/grpc_server.o: src/grpc/grpc_server.cpp.o
.PHONY : src/grpc/grpc_server.o

# target to build an object file
src/grpc/grpc_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_service.dir/build.make CMakeFiles/grpc_service.dir/src/grpc/grpc_server.cpp.o
.PHONY : src/grpc/grpc_server.cpp.o

src/grpc/grpc_server.i: src/grpc/grpc_server.cpp.i
.PHONY : src/grpc/grpc_server.i

# target to preprocess a source file
src/grpc/grpc_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_service.dir/build.make CMakeFiles/grpc_service.dir/src/grpc/grpc_server.cpp.i
.PHONY : src/grpc/grpc_server.cpp.i

src/grpc/grpc_server.s: src/grpc/grpc_server.cpp.s
.PHONY : src/grpc/grpc_server.s

# target to generate assembly for a file
src/grpc/grpc_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_service.dir/build.make CMakeFiles/grpc_service.dir/src/grpc/grpc_server.cpp.s
.PHONY : src/grpc/grpc_server.cpp.s

src/grpc/wasm_service_impl.o: src/grpc/wasm_service_impl.cpp.o
.PHONY : src/grpc/wasm_service_impl.o

# target to build an object file
src/grpc/wasm_service_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_service.dir/build.make CMakeFiles/grpc_service.dir/src/grpc/wasm_service_impl.cpp.o
.PHONY : src/grpc/wasm_service_impl.cpp.o

src/grpc/wasm_service_impl.i: src/grpc/wasm_service_impl.cpp.i
.PHONY : src/grpc/wasm_service_impl.i

# target to preprocess a source file
src/grpc/wasm_service_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_service.dir/build.make CMakeFiles/grpc_service.dir/src/grpc/wasm_service_impl.cpp.i
.PHONY : src/grpc/wasm_service_impl.cpp.i

src/grpc/wasm_service_impl.s: src/grpc/wasm_service_impl.cpp.s
.PHONY : src/grpc/wasm_service_impl.s

# target to generate assembly for a file
src/grpc/wasm_service_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_service.dir/build.make CMakeFiles/grpc_service.dir/src/grpc/wasm_service_impl.cpp.s
.PHONY : src/grpc/wasm_service_impl.cpp.s

src/sql/sql_engine.o: src/sql/sql_engine.cpp.o
.PHONY : src/sql/sql_engine.o

# target to build an object file
src/sql/sql_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sql_engine.dir/build.make CMakeFiles/sql_engine.dir/src/sql/sql_engine.cpp.o
.PHONY : src/sql/sql_engine.cpp.o

src/sql/sql_engine.i: src/sql/sql_engine.cpp.i
.PHONY : src/sql/sql_engine.i

# target to preprocess a source file
src/sql/sql_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sql_engine.dir/build.make CMakeFiles/sql_engine.dir/src/sql/sql_engine.cpp.i
.PHONY : src/sql/sql_engine.cpp.i

src/sql/sql_engine.s: src/sql/sql_engine.cpp.s
.PHONY : src/sql/sql_engine.s

# target to generate assembly for a file
src/sql/sql_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sql_engine.dir/build.make CMakeFiles/sql_engine.dir/src/sql/sql_engine.cpp.s
.PHONY : src/sql/sql_engine.cpp.s

src/storage/mem_table.o: src/storage/mem_table.cpp.o
.PHONY : src/storage/mem_table.o

# target to build an object file
src/storage/mem_table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/storage.dir/build.make CMakeFiles/storage.dir/src/storage/mem_table.cpp.o
.PHONY : src/storage/mem_table.cpp.o

src/storage/mem_table.i: src/storage/mem_table.cpp.i
.PHONY : src/storage/mem_table.i

# target to preprocess a source file
src/storage/mem_table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/storage.dir/build.make CMakeFiles/storage.dir/src/storage/mem_table.cpp.i
.PHONY : src/storage/mem_table.cpp.i

src/storage/mem_table.s: src/storage/mem_table.cpp.s
.PHONY : src/storage/mem_table.s

# target to generate assembly for a file
src/storage/mem_table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/storage.dir/build.make CMakeFiles/storage.dir/src/storage/mem_table.cpp.s
.PHONY : src/storage/mem_table.cpp.s

src/storage/storage_engine.o: src/storage/storage_engine.cpp.o
.PHONY : src/storage/storage_engine.o

# target to build an object file
src/storage/storage_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/storage.dir/build.make CMakeFiles/storage.dir/src/storage/storage_engine.cpp.o
.PHONY : src/storage/storage_engine.cpp.o

src/storage/storage_engine.i: src/storage/storage_engine.cpp.i
.PHONY : src/storage/storage_engine.i

# target to preprocess a source file
src/storage/storage_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/storage.dir/build.make CMakeFiles/storage.dir/src/storage/storage_engine.cpp.i
.PHONY : src/storage/storage_engine.cpp.i

src/storage/storage_engine.s: src/storage/storage_engine.cpp.s
.PHONY : src/storage/storage_engine.s

# target to generate assembly for a file
src/storage/storage_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/storage.dir/build.make CMakeFiles/storage.dir/src/storage/storage_engine.cpp.s
.PHONY : src/storage/storage_engine.cpp.s

src/storage/transaction_impl.o: src/storage/transaction_impl.cpp.o
.PHONY : src/storage/transaction_impl.o

# target to build an object file
src/storage/transaction_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/storage.dir/build.make CMakeFiles/storage.dir/src/storage/transaction_impl.cpp.o
.PHONY : src/storage/transaction_impl.cpp.o

src/storage/transaction_impl.i: src/storage/transaction_impl.cpp.i
.PHONY : src/storage/transaction_impl.i

# target to preprocess a source file
src/storage/transaction_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/storage.dir/build.make CMakeFiles/storage.dir/src/storage/transaction_impl.cpp.i
.PHONY : src/storage/transaction_impl.cpp.i

src/storage/transaction_impl.s: src/storage/transaction_impl.cpp.s
.PHONY : src/storage/transaction_impl.s

# target to generate assembly for a file
src/storage/transaction_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/storage.dir/build.make CMakeFiles/storage.dir/src/storage/transaction_impl.cpp.s
.PHONY : src/storage/transaction_impl.cpp.s

src/storage/wal_impl.o: src/storage/wal_impl.cpp.o
.PHONY : src/storage/wal_impl.o

# target to build an object file
src/storage/wal_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/storage.dir/build.make CMakeFiles/storage.dir/src/storage/wal_impl.cpp.o
.PHONY : src/storage/wal_impl.cpp.o

src/storage/wal_impl.i: src/storage/wal_impl.cpp.i
.PHONY : src/storage/wal_impl.i

# target to preprocess a source file
src/storage/wal_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/storage.dir/build.make CMakeFiles/storage.dir/src/storage/wal_impl.cpp.i
.PHONY : src/storage/wal_impl.cpp.i

src/storage/wal_impl.s: src/storage/wal_impl.cpp.s
.PHONY : src/storage/wal_impl.s

# target to generate assembly for a file
src/storage/wal_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/storage.dir/build.make CMakeFiles/storage.dir/src/storage/wal_impl.cpp.s
.PHONY : src/storage/wal_impl.cpp.s

src/wasm/wasm_engine.o: src/wasm/wasm_engine.cpp.o
.PHONY : src/wasm/wasm_engine.o

# target to build an object file
src/wasm/wasm_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasm_engine.dir/build.make CMakeFiles/wasm_engine.dir/src/wasm/wasm_engine.cpp.o
.PHONY : src/wasm/wasm_engine.cpp.o

src/wasm/wasm_engine.i: src/wasm/wasm_engine.cpp.i
.PHONY : src/wasm/wasm_engine.i

# target to preprocess a source file
src/wasm/wasm_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasm_engine.dir/build.make CMakeFiles/wasm_engine.dir/src/wasm/wasm_engine.cpp.i
.PHONY : src/wasm/wasm_engine.cpp.i

src/wasm/wasm_engine.s: src/wasm/wasm_engine.cpp.s
.PHONY : src/wasm/wasm_engine.s

# target to generate assembly for a file
src/wasm/wasm_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasm_engine.dir/build.make CMakeFiles/wasm_engine.dir/src/wasm/wasm_engine.cpp.s
.PHONY : src/wasm/wasm_engine.cpp.s

src/wasm/wasm_subscription.o: src/wasm/wasm_subscription.cpp.o
.PHONY : src/wasm/wasm_subscription.o

# target to build an object file
src/wasm/wasm_subscription.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasm_engine.dir/build.make CMakeFiles/wasm_engine.dir/src/wasm/wasm_subscription.cpp.o
.PHONY : src/wasm/wasm_subscription.cpp.o

src/wasm/wasm_subscription.i: src/wasm/wasm_subscription.cpp.i
.PHONY : src/wasm/wasm_subscription.i

# target to preprocess a source file
src/wasm/wasm_subscription.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasm_engine.dir/build.make CMakeFiles/wasm_engine.dir/src/wasm/wasm_subscription.cpp.i
.PHONY : src/wasm/wasm_subscription.cpp.i

src/wasm/wasm_subscription.s: src/wasm/wasm_subscription.cpp.s
.PHONY : src/wasm/wasm_subscription.s

# target to generate assembly for a file
src/wasm/wasm_subscription.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasm_engine.dir/build.make CMakeFiles/wasm_engine.dir/src/wasm/wasm_subscription.cpp.s
.PHONY : src/wasm/wasm_subscription.cpp.s

src/websocket/websocket_server.o: src/websocket/websocket_server.cpp.o
.PHONY : src/websocket/websocket_server.o

# target to build an object file
src/websocket/websocket_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_server.dir/build.make CMakeFiles/websocket_server.dir/src/websocket/websocket_server.cpp.o
.PHONY : src/websocket/websocket_server.cpp.o

src/websocket/websocket_server.i: src/websocket/websocket_server.cpp.i
.PHONY : src/websocket/websocket_server.i

# target to preprocess a source file
src/websocket/websocket_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_server.dir/build.make CMakeFiles/websocket_server.dir/src/websocket/websocket_server.cpp.i
.PHONY : src/websocket/websocket_server.cpp.i

src/websocket/websocket_server.s: src/websocket/websocket_server.cpp.s
.PHONY : src/websocket/websocket_server.s

# target to generate assembly for a file
src/websocket/websocket_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_server.dir/build.make CMakeFiles/websocket_server.dir/src/websocket/websocket_server.cpp.s
.PHONY : src/websocket/websocket_server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... changefeed_engine"
	@echo "... common_lib"
	@echo "... fmt"
	@echo "... grpc_service"
	@echo "... instantdb"
	@echo "... instantdb_client"
	@echo "... instantdb_demo"
	@echo "... instantdb_init"
	@echo "... instantdb_server"
	@echo "... instantdb_sql"
	@echo "... spdlog"
	@echo "... sql_engine"
	@echo "... storage"
	@echo "... wasm_engine"
	@echo "... websocket_server"
	@echo "... generated/instantdb.grpc.pb.o"
	@echo "... generated/instantdb.grpc.pb.i"
	@echo "... generated/instantdb.grpc.pb.s"
	@echo "... generated/instantdb.pb.o"
	@echo "... generated/instantdb.pb.i"
	@echo "... generated/instantdb.pb.s"
	@echo "... src/changefeed/changefeed_engine.o"
	@echo "... src/changefeed/changefeed_engine.i"
	@echo "... src/changefeed/changefeed_engine.s"
	@echo "... src/changefeed/sql_subscription.o"
	@echo "... src/changefeed/sql_subscription.i"
	@echo "... src/changefeed/sql_subscription.s"
	@echo "... src/cmd/grpc_client.o"
	@echo "... src/cmd/grpc_client.i"
	@echo "... src/cmd/grpc_client.s"
	@echo "... src/cmd/instantdb_cli.o"
	@echo "... src/cmd/instantdb_cli.i"
	@echo "... src/cmd/instantdb_cli.s"
	@echo "... src/cmd/instantdb_init.o"
	@echo "... src/cmd/instantdb_init.i"
	@echo "... src/cmd/instantdb_init.s"
	@echo "... src/cmd/instantdb_server.o"
	@echo "... src/cmd/instantdb_server.i"
	@echo "... src/cmd/instantdb_server.s"
	@echo "... src/cmd/prototype_demo.o"
	@echo "... src/cmd/prototype_demo.i"
	@echo "... src/cmd/prototype_demo.s"
	@echo "... src/cmd/sql_demo.o"
	@echo "... src/cmd/sql_demo.i"
	@echo "... src/cmd/sql_demo.s"
	@echo "... src/common/config.o"
	@echo "... src/common/config.i"
	@echo "... src/common/config.s"
	@echo "... src/common/metrics.o"
	@echo "... src/common/metrics.i"
	@echo "... src/common/metrics.s"
	@echo "... src/grpc/grpc_server.o"
	@echo "... src/grpc/grpc_server.i"
	@echo "... src/grpc/grpc_server.s"
	@echo "... src/grpc/wasm_service_impl.o"
	@echo "... src/grpc/wasm_service_impl.i"
	@echo "... src/grpc/wasm_service_impl.s"
	@echo "... src/sql/sql_engine.o"
	@echo "... src/sql/sql_engine.i"
	@echo "... src/sql/sql_engine.s"
	@echo "... src/storage/mem_table.o"
	@echo "... src/storage/mem_table.i"
	@echo "... src/storage/mem_table.s"
	@echo "... src/storage/storage_engine.o"
	@echo "... src/storage/storage_engine.i"
	@echo "... src/storage/storage_engine.s"
	@echo "... src/storage/transaction_impl.o"
	@echo "... src/storage/transaction_impl.i"
	@echo "... src/storage/transaction_impl.s"
	@echo "... src/storage/wal_impl.o"
	@echo "... src/storage/wal_impl.i"
	@echo "... src/storage/wal_impl.s"
	@echo "... src/wasm/wasm_engine.o"
	@echo "... src/wasm/wasm_engine.i"
	@echo "... src/wasm/wasm_engine.s"
	@echo "... src/wasm/wasm_subscription.o"
	@echo "... src/wasm/wasm_subscription.i"
	@echo "... src/wasm/wasm_subscription.s"
	@echo "... src/websocket/websocket_server.o"
	@echo "... src/websocket/websocket_server.i"
	@echo "... src/websocket/websocket_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

